// Placeholder only. Real FlutterFire options are generated by FlutterFire CLI.
class DefaultFirebaseOptions {
  static const currentPlatform = <String, String>{
    'projectId': 'sample-project',
  };
}
